# Generated by Django 5.0.3 on 2024-03-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('hyper_tension_bp', models.BooleanField(default=False)),
                ('chest_pain', models.BooleanField(default=False)),
                ('palpitation', models.BooleanField(default=False)),
                ('surgery', models.BooleanField(default=False)),
                ('any_other', models.TextField(max_length=50)),
            ],
        ),
    ]
