# Generated by Django 5.0.3 on 2024-03-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('health_condition', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='chest_pain',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='hyper_tension_bp',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='palpitation',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='surgery',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=50),
        ),
    ]
