# Generated by Django 5.0.3 on 2024-03-19 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_details', '0003_delete_doctor_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_details',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patient_details',
            name='name',
            field=models.CharField(default='patient', max_length=100),
        ),
        migrations.AddField(
            model_name='patient_details',
            name='phone_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
