# Generated by Django 5.0.3 on 2024-03-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_details', '0005_alter_patient_details_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_details',
            name='age',
            field=models.CharField(max_length=200),
        ),
    ]
