# Generated by Django 5.0.3 on 2024-03-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_details', '0006_alter_patient_details_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_details',
            name='height',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='weight',
            field=models.CharField(max_length=5),
        ),
    ]
