# Generated by Django 5.0.3 on 2024-04-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_details', '0008_patient_details_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_details',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='any_other',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='chest_pain',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='hyper_tension_bp',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='palpitation',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='phone_number',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='surgery',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
