# Generated by Django 5.0.3 on 2024-04-06 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_details', '0009_alter_patient_details_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_details',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='phone_number',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='recordings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.FileField(upload_to='recordfile')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_details.patient_details')),
            ],
        ),
    ]
