# Generated by Django 5.0.3 on 2024-04-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_details', '0010_alter_patient_details_height_and_more'),
        ('patient_details', '0013_alter_patient_details_chest_pain_and_more'),
    ]

    operations = [
    ]
