# Generated by Django 5.0.3 on 2024-04-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_details', '0015_alter_patient_details_chest_pain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_details',
            name='chest_pain',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='hyper_tension_bp',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='palpitation',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='surgery',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=100),
        ),
    ]
