# Generated by Django 5.0.3 on 2024-03-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor_details',
        ),
    ]
