# Generated by Django 5.0.3 on 2024-03-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_details', '0002_doctor_profile_delete_doctor_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='doctor_profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor_profile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='doctor_profile',
            name='specialty',
        ),
    ]
