# Generated by Django 5.0.3 on 2024-03-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_details', '0003_remove_doctor_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='license_no',
            field=models.CharField(default='XXXXX', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='specialty',
            field=models.CharField(default='XXXXX', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='doctor_name',
            field=models.CharField(default='DOCTOR', max_length=50),
        ),
    ]
