# Generated by Django 5.0.3 on 2024-04-04 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_details', '0004_doctor_profile_bio_doctor_profile_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_profile',
            name='auth',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_details', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
